services:
  job-application:
    build: .
    ports:
      - "4004:4004"
    env_file:
      - .env
    volumes:
      - application-data:/app/db
    restart: unless-stopped

volumes:
  application-data:
